title: Podel Bot
description: The best Podel related bot on the internet.
show_downloads: true
github:
  zip_url: https://github.com/Podelsoft/Podel/archive/v1.4.5.zip
  tar.gz_url: https://github.com/Podelsoft/Podel/archive/v1.4.5.tar.gz
google_analytics:
theme: jekyll-theme-hacker
